version: '3'
# networks: 
#   vtnga-network:
#     external: true
services:
  ruscoffee:
    image: ruscoffee
    container_name: ruscoffee_container
    restart: always
#     networks:
#       - vtnga-network
    ports:
      - '8001:80'
    build:
      context: .
      dockerfile: RusCoffee/Dockerfile
